# Shell variables
# Generated by 'wal'
wallpaper='/home/naom/Pictures/backgrounds/cropped-1920-1080-1050844.jpg'

# Special
background='#0f0f0f'
foreground='#c4c0c6'
cursor='#c4c0c6'

# Colors
color0='#0f0f0f'
color1='#6B6E70'
color2='#8E706B'
color3='#AF9D6A'
color4='#71768A'
color5='#8D788C'
color6='#798694'
color7='#c4c0c6'
color8='#89868a'
color9='#6B6E70'
color10='#8E706B'
color11='#AF9D6A'
color12='#71768A'
color13='#8D788C'
color14='#798694'
color15='#c4c0c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
