--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/naom/Pictures/backgrounds/cropped-1920-1080-1050844.jpg"

-- Special
background="#0f0f0f"
foreground="#c4c0c6"
cursor="#c4c0c6"

-- Colors
color0="#0f0f0f"
color1="#6B6E70"
color2="#8E706B"
color3="#AF9D6A"
color4="#71768A"
color5="#8D788C"
color6="#798694"
color7="#c4c0c6"
color8="#89868a"
color9="#6B6E70"
color10="#8E706B"
color11="#AF9D6A"
color12="#71768A"
color13="#8D788C"
color14="#798694"
color15="#c4c0c6"
